language: python
python:
  - '3.6'

install:
  - script/bootstrap
  - pip install codacy-coverage

script:
  - script/test --cov=ddl

after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml
