language: python
python:
  - '3.6'

install:
  - script/bootstrap
  - pip install codacy-coverage

script:
  - script/test

after_success:
  - python-codacy-coverage -r coverage.xml

env:
  global:
    secure: n/HXNwLkVORr8Qk9V9sJmY2kTCb+fMfvdRKK5AsfCsFOjpkU2kq8PnlJfHxp78DiB39IFL3XT7k6aS84R4d262yPULcUsByzT+Iu0WwVllQkcHpLsJ5BWhEMzz55BvWdNQwYOhpsnDm4N5FlVqHZRydm92kWITY4r26QqTN1gzMaXuGAMUINxNzmofN3FyQf7STSIT9XD+jj+IfPgvhk7KPYMdAGmxgDuR98fMRCp6Bmj/0GInZzydcJAZ6UjLBzWVN6LgMhDSk6vnew4hnrufR8sVvbvo8u5+2fsqDTlyuIX2t93MxDw8fIdJl2OQcCntTxkGkQ9yDTIt1jK3RiEzHNHm8pQ8fx++EbsB47XTXTCE+zS4zmQ3Jd/k2Few5m0AivejfyX2rp9m644yupBQof7QW7D3DXdvDNYoI5IC1DN8xJknvhNC6a3YqrUOkHOkIfpPbHTA+yRQTl+claCThtZQs5/OQoUiNI/2heqo9uxtFe5kBadrT1J18fIUXIuVC4v+5V8dAjLffD8E/REwjc9eoCfmPL7xmilwu4EMpdsok41sQGhLnVNsemyFVu/inIf4osFYclLCJi+55/Bfcl6xabQTHE9IXhsiRHI4VG1PPIFfo/tQcS/t/WTUISnLDGIoRt1E+3CZwNVspc4NPT0x+TxguVjOCLR5Q0hlI=
